# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b35a8b78cd3f80b8b1ca0c32b125f6b5a5fda52abe5dc687f3e24da397cf7b2a2d36f074cb116c84a599b53cef036d8928249f4cc266b9f5a6f6339eb46ed355

test:
  secret_key_base: 1ae99376e15a5db7b3e2e6847270599f20a34e2d08e390367de9887ccc7ac88b36824f8bcccee58970b6abdadb7dbce9dde85b982a9b0f6905158fc1016bcf2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
